# Generated by Django 3.2.15 on 2022-08-20 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='İlan Başlığı')),
                ('content', models.TextField(verbose_name='İlan Açıklama')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='İlan Resmi')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('map_location', models.TextField(blank=True, null=True, verbose_name="Harita Konumu<br><em class='em12'>Örnek : https://www.google.com/maps/embed?pb=xxxxxxxxx</em>")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
